name: 'Create release branch from tag'
description: 'create release branch from tag pushed by the user'
outputs:
  scriptOutput:
    description: "script output"
    value: ''
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/create_branch_list.sh
      shell: bash
    - run: ${{github.action_path}}/get_latest_release.py
      shell: python
    - run: ${{ github.action_path }}/remove_branch_list.sh
      shell: bash
