# This is a basic workflow to help you get started with Actions
name: Daily dev update
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 4'

jobs:
  # This workflow contains a single job called "build"
  #build:
  merge-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Shallow clone divvy-dev
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: main
      - name: Shallow clone alcide-github-actions
        uses: actions/checkout@v2
        with:
          repository: rapid7/alcide-github-actions
          path: aux
          fetch-depth: 0
      - name: Create list of branches
        run:  |
          ls -la
          cd main
          ls -la
          git branch -a
          echo "Copying filtered branches to file."
          git branch -a | grep -E '/release/(([0-9])+\.)+([0-9])+$' > /aux/alcide-github-actions/create-mergeback-from-release/branches
                 echo "File created successfully."
      - name: Get latest version branch name
        run: |
          ls -la
          cd /aux/alcide-github-actions/create-mergeback-from-release/
          ls -la
          chmod 777 get_latest_release.py
          output=$(python ./get_latest_release.py)
          echo "$output"
          echo "::set-output name=latest_semver::$output"
          chmod 777 branch.sh
          chmod 777 action.yml
          chmod 777 common.sh
          ls -la
          cd ..
          ls -la
        id: semver
      - name: Create new mergeback__version_date branch
        uses: rapid7/alcide-github-actions/create-mergeback-branch-from-release@master
        with:
          versionName: ${{steps.semver.outputs.latest_semver}}
          gitUserName: "'Moran Rotman'"
          gitUserEmail: "'moran_rotman@rapid7.com'"
          gitToken: ${{github.token}}
      - name: Delete branch list
        run:  |
          cd /aux/alcide-github-actions/create-mergeback-from-release/
          ls -la
          echo "deleting branch list"
          rm branches
          ls -la
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!
      #
      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
