# This is a basic workflow to help you get started with Actions
name: Daily dev update
# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 4'

jobs:
  # This workflow contains a single job called "build"
  #build:
  merge-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Shallow clone divvy-dev
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create list of branches
        run:  |
          ls -la
          git branch -a
          echo "Copying filtered branches to file."
          git branch -a | grep -E '/release/(([0-9])+\.)+([0-9])+$' > get_latest_branch/branches
                 echo "File created successfully."
      - name: Get latest version branch branch name
        run: |
          cd get_latest_branch
          chmod 777 get_latest_release.py
          output=$(python ./get_latest_release.py)
          echo "$output"
          echo "::set-output name=latest_semver::$output"
          cd ..
          cd create-mergeback-branch-from-release
          ls -la
          chmod 777 branch.sh
          chmod 777 action.yml
          chmod 777 common.sh
          ls -la
          cd ..
          echo "Configuring git creds"
          git config --global user.name "Moran Rotman"
          git config --global user.email "moran_rotman@rapid7.com"
          
        id: semver
      - name: Create new mergeback__version_date branch
        #uses: actions/checkout@v2
        uses: mrotman-r7/test-actions/create-mergeback-branch-from-release@no_directory
        with:
          versionName: ${{steps.semver.outputs.latest_semver}}
          gitUserName: "'Moran Rotman'"
          gitUserEmail: "'moran_rotman@rapid7.com'"
      - name: Delete branch list
        run:  |
          echo "deleting branch list"
          rm branches
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!
      #
      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
